# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 380)
        Dialog.setStyleSheet("QDialog {\n"
"    background-color: #F7F5F0;\n"
"}\n"
"QLabel {\n"
"    color: #1A2A4A;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #D1D5DB;\n"
"    border-radius: 7px;\n"
"    padding: 10px 12px;\n"
"    font-size: 13px;\n"
"    color: #1A2A4A;\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1.5px solid #2F80ED;\n"
"}\n"
"QPushButton#BtnLogin {\n"
"    background-color: #1A2A4A;\n"
"    color: #FFFFFF;\n"
"    padding: 10px;\n"
"    border-radius: 7px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"}\n"
"QPushButton#BtnLogin:hover {\n"
"    background-color: #C9A84C;\n"
"    color: #1A2A4A;\n"
"}\n"
"QPushButton#BtnLogin:pressed {\n"
"    background-color: #0F1B30;\n"
"}")
        self.dialogLayout = QtWidgets.QVBoxLayout(Dialog)
        self.dialogLayout.setContentsMargins(48, 36, 48, 36)
        self.dialogLayout.setSpacing(14)
        self.dialogLayout.setObjectName("dialogLayout")
        self.lbl_app_title = QtWidgets.QLabel(parent=Dialog)
        self.lbl_app_title.setStyleSheet("color: #1A2A4A;\n"
"font-size: 20px;\n"
"font-weight: bold;\n"
"padding-bottom: 8px;")
        self.lbl_app_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_app_title.setObjectName("lbl_app_title")
        self.dialogLayout.addWidget(self.lbl_app_title)
        self.divider = QtWidgets.QFrame(parent=Dialog)
        self.divider.setStyleSheet("background-color: #C9A84C;")
        self.divider.setMaximumSize(QtCore.QSize(16777215, 2))
        self.divider.setMinimumSize(QtCore.QSize(0, 2))
        self.divider.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.divider.setObjectName("divider")
        self.dialogLayout.addWidget(self.divider)
        spacerItem = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.dialogLayout.addItem(spacerItem)
        self.lbl_username = QtWidgets.QLabel(parent=Dialog)
        self.lbl_username.setObjectName("lbl_username")
        self.dialogLayout.addWidget(self.lbl_username)
        self.inp_username = QtWidgets.QLineEdit(parent=Dialog)
        self.inp_username.setObjectName("inp_username")
        self.dialogLayout.addWidget(self.inp_username)
        self.lbl_password = QtWidgets.QLabel(parent=Dialog)
        self.lbl_password.setObjectName("lbl_password")
        self.dialogLayout.addWidget(self.lbl_password)
        self.inp_password = QtWidgets.QLineEdit(parent=Dialog)
        self.inp_password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.inp_password.setObjectName("inp_password")
        self.dialogLayout.addWidget(self.inp_password)
        spacerItem1 = QtWidgets.QSpacerItem(20, 8, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.dialogLayout.addItem(spacerItem1)
        self.BtnLogin = QtWidgets.QPushButton(parent=Dialog)
        self.BtnLogin.setAutoDefault(True)
        self.BtnLogin.setObjectName("BtnLogin")
        self.dialogLayout.addWidget(self.BtnLogin)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Login – Hotel Management"))
        self.lbl_app_title.setText(_translate("Dialog", "🏨 HOTEL MANAGEMENT SYSTEM"))
        self.lbl_username.setText(_translate("Dialog", "Tên đăng nhập"))
        self.inp_username.setPlaceholderText(_translate("Dialog", "Nhập tên đăng nhập..."))
        self.lbl_password.setText(_translate("Dialog", "Mật khẩu"))
        self.inp_password.setPlaceholderText(_translate("Dialog", "Nhập mật khẩu..."))
        self.BtnLogin.setText(_translate("Dialog", "Đăng Nhập"))
