# Form implementation generated from reading ui file 'Staff.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StaffWindow(object):
    def setupUi(self, StaffWindow):
        StaffWindow.setObjectName("StaffWindow")
        StaffWindow.resize(1280, 760)
        StaffWindow.setStyleSheet("QMainWindow { background-color: #F7F5F0; border: none; }\n"
"QStatusBar, QMenuBar { background: #1A2A4A; color: #C9A84C; border: none; }")
        self.centralwidget = QtWidgets.QWidget(parent=StaffWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rootLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.rootLayout.setContentsMargins(0, 0, 0, 0)
        self.rootLayout.setSpacing(0)
        self.rootLayout.setObjectName("rootLayout")
        self.sidebar = QtWidgets.QFrame(parent=self.centralwidget)
        self.sidebar.setMinimumSize(QtCore.QSize(250, 0))
        self.sidebar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.sidebar.setStyleSheet("\n"
"/* Sidebar nền */\n"
"QFrame#sidebar {\n"
"    background-color: #1A2A4A;\n"
"    border: none;\n"
"    border-right: 2px solid #C9A84C;\n"
"}\n"
"/* Label tiêu đề */\n"
"QLabel#lbl_app_title {\n"
"    background-color: #12213A;\n"
"    color: #C9A84C;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    padding: 18px 12px;\n"
"    border-bottom: 2px solid #C9A84C;\n"
"    border-right: none;\n"
"}\n"
"/* Tất cả nút nav */\n"
"QFrame#sidebar QPushButton {\n"
"    background-color: transparent;\n"
"    color: #B8C4D8;\n"
"    font-size: 13px;\n"
"    font-weight: 500;\n"
"    text-align: left;\n"
"    padding: 12px 18px;\n"
"    border: none;\n"
"    border-left: 3px solid transparent;\n"
"    border-radius: 0px;\n"
"}\n"
"QFrame#sidebar QPushButton:hover {\n"
"    background-color: #243558;\n"
"    color: #FFFFFF;\n"
"    border-left: 3px solid #C9A84C;\n"
"}\n"
"/* Trạng thái active — set từ code bằng setProperty */\n"
"QFrame#sidebar QPushButton[active=true] {\n"
"    background-color: #2C4070;\n"
"    color: #FFFFFF;\n"
"    border-left: 3px solid #C9A84C;\n"
"    font-weight: bold;\n"
"}\n"
"/* Nút logout riêng */\n"
"QPushButton#btn_logout {\n"
"    background-color: transparent;\n"
"    color: #E8A0A0;\n"
"    font-size: 13px;\n"
"    text-align: left;\n"
"    padding: 12px 18px;\n"
"    border: none;\n"
"    border-top: 1px solid #2A3D5E;\n"
"    border-left: 3px solid transparent;\n"
"    border-radius: 0px;\n"
"}\n"
"QPushButton#btn_logout:hover {\n"
"    background-color: #4A1818;\n"
"    color: #FFFFFF;\n"
"    border-left: 3px solid #E8A0A0;\n"
"}\n"
"       ")
        self.sidebar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.sidebar.setObjectName("sidebar")
        self.sidebarInner = QtWidgets.QVBoxLayout(self.sidebar)
        self.sidebarInner.setContentsMargins(0, 0, 0, 0)
        self.sidebarInner.setSpacing(0)
        self.sidebarInner.setObjectName("sidebarInner")
        self.lbl_app_title = QtWidgets.QLabel(parent=self.sidebar)
        self.lbl_app_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_app_title.setObjectName("lbl_app_title")
        self.sidebarInner.addWidget(self.lbl_app_title)
        self.btn_nav_checkin = QtWidgets.QPushButton(parent=self.sidebar)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(62)
        self.btn_nav_checkin.setFont(font)
        self.btn_nav_checkin.setCheckable(False)
        self.btn_nav_checkin.setObjectName("btn_nav_checkin")
        self.sidebarInner.addWidget(self.btn_nav_checkin)
        self.btn_nav_checkout = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_nav_checkout.setCheckable(False)
        self.btn_nav_checkout.setObjectName("btn_nav_checkout")
        self.sidebarInner.addWidget(self.btn_nav_checkout)
        self.btn_nav_rooms = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_nav_rooms.setCheckable(False)
        self.btn_nav_rooms.setObjectName("btn_nav_rooms")
        self.sidebarInner.addWidget(self.btn_nav_rooms)
        self.btn_nav_invoice = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_nav_invoice.setCheckable(False)
        self.btn_nav_invoice.setObjectName("btn_nav_invoice")
        self.sidebarInner.addWidget(self.btn_nav_invoice)
        self.btn_nav_service = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_nav_service.setCheckable(False)
        self.btn_nav_service.setObjectName("btn_nav_service")
        self.sidebarInner.addWidget(self.btn_nav_service)
        self.btn_nav_profile = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_nav_profile.setCheckable(False)
        self.btn_nav_profile.setObjectName("btn_nav_profile")
        self.sidebarInner.addWidget(self.btn_nav_profile)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.sidebarInner.addItem(spacerItem)
        self.btn_logout = QtWidgets.QPushButton(parent=self.sidebar)
        self.btn_logout.setCheckable(False)
        self.btn_logout.setObjectName("btn_logout")
        self.sidebarInner.addWidget(self.btn_logout)
        self.rootLayout.addWidget(self.sidebar)
        self.MainContent = QtWidgets.QFrame(parent=self.centralwidget)
        self.MainContent.setStyleSheet("QFrame#MainContent { background-color: #F7F5F0; border: none; }")
        self.MainContent.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.MainContent.setObjectName("MainContent")
        self.mainLayout = QtWidgets.QVBoxLayout(self.MainContent)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.Header = QtWidgets.QFrame(parent=self.MainContent)
        self.Header.setMinimumSize(QtCore.QSize(0, 54))
        self.Header.setMaximumSize(QtCore.QSize(16777215, 54))
        self.Header.setStyleSheet("QFrame#Header {\n"
"    background-color: #FFFFFF;\n"
"    border: none;\n"
"    border-bottom: 2px solid #C9A84C;\n"
"}")
        self.Header.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Header.setObjectName("Header")
        self.headerLayout = QtWidgets.QHBoxLayout(self.Header)
        self.headerLayout.setContentsMargins(20, 0, 20, 0)
        self.headerLayout.setObjectName("headerLayout")
        self.lbl_header_title = QtWidgets.QLabel(parent=self.Header)
        self.lbl_header_title.setStyleSheet("color: #1A2A4A; font-size: 17px; font-weight: bold; border: none;")
        self.lbl_header_title.setObjectName("lbl_header_title")
        self.headerLayout.addWidget(self.lbl_header_title)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem1)
        self.lbl_current_user = QtWidgets.QLabel(parent=self.Header)
        self.lbl_current_user.setStyleSheet("color: #6B7896; font-size: 13px; border: none; padding-right: 6px;")
        self.lbl_current_user.setObjectName("lbl_current_user")
        self.headerLayout.addWidget(self.lbl_current_user)
        self.mainLayout.addWidget(self.Header)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.MainContent)
        self.stackedWidget.setStyleSheet("QStackedWidget { background-color: #F7F5F0; border: none; }")
        self.stackedWidget.setObjectName("stackedWidget")
        self.pg_checkin = QtWidgets.QWidget()
        self.pg_checkin.setObjectName("pg_checkin")
        self.checkinPageLayout = QtWidgets.QVBoxLayout(self.pg_checkin)
        self.checkinPageLayout.setContentsMargins(24, 20, 24, 20)
        self.checkinPageLayout.setSpacing(16)
        self.checkinPageLayout.setObjectName("checkinPageLayout")
        self.lbl_checkin_page_title = QtWidgets.QLabel(parent=self.pg_checkin)
        self.lbl_checkin_page_title.setStyleSheet("color: #1A2A4A; font-size: 16px; font-weight: bold; border: none;")
        self.lbl_checkin_page_title.setObjectName("lbl_checkin_page_title")
        self.checkinPageLayout.addWidget(self.lbl_checkin_page_title)
        self.fra_checkin_form = QtWidgets.QFrame(parent=self.pg_checkin)
        self.fra_checkin_form.setStyleSheet("QFrame#fra_checkin_form {\n"
"    background-color: #FFFFFF;\n"
"    border: 1px solid #DDD8D0;\n"
"    border-radius: 12px;\n"
"}\n"
"QLabel {\n"
"    color: #1A2B4A;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    background: transparent;\n"
"}\n"
"QLineEdit, QComboBox, QDateEdit {\n"
"    background-color: #F9F9F9;\n"
"    border: 1.5px solid #D1D5DB;\n"
"    border-radius: 7px;\n"
"    padding: 9px 12px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"}\n"
"QLineEdit:focus, QDateEdit:focus {\n"
"    border: 1.5px solid #C9A84C;\n"
"    background-color: #FFFEF9;\n"
"}\n"
"QComboBox:focus { border: 1.5px solid #C9A84C; }\n"
"QComboBox::drop-down { border: none; width: 26px; }\n"
"QComboBox QAbstractItemView {\n"
"    background: #FFF; border: 1px solid #1A2B4A;\n"
"    selection-background-color: #EAF2FB; color: #1A2B4A;\n"
"}\n"
"              ")
        self.fra_checkin_form.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.fra_checkin_form.setObjectName("fra_checkin_form")
        self.checkinGrid = QtWidgets.QGridLayout(self.fra_checkin_form)
        self.checkinGrid.setContentsMargins(28, 24, 28, 24)
        self.checkinGrid.setHorizontalSpacing(20)
        self.checkinGrid.setVerticalSpacing(14)
        self.checkinGrid.setObjectName("checkinGrid")
        self.lbl_ci_name = QtWidgets.QLabel(parent=self.fra_checkin_form)
        self.lbl_ci_name.setObjectName("lbl_ci_name")
        self.checkinGrid.addWidget(self.lbl_ci_name, 0, 0, 1, 1)
        self.inp_ci_name = QtWidgets.QLineEdit(parent=self.fra_checkin_form)
        self.inp_ci_name.setObjectName("inp_ci_name")
        self.checkinGrid.addWidget(self.inp_ci_name, 0, 1, 1, 1)
        self.lbl_ci_idcard = QtWidgets.QLabel(parent=self.fra_checkin_form)
        self.lbl_ci_idcard.setObjectName("lbl_ci_idcard")
        self.checkinGrid.addWidget(self.lbl_ci_idcard, 0, 2, 1, 1)
        self.inp_ci_idcard = QtWidgets.QLineEdit(parent=self.fra_checkin_form)
        self.inp_ci_idcard.setObjectName("inp_ci_idcard")
        self.checkinGrid.addWidget(self.inp_ci_idcard, 0, 3, 1, 1)
        self.lbl_ci_phone = QtWidgets.QLabel(parent=self.fra_checkin_form)
        self.lbl_ci_phone.setObjectName("lbl_ci_phone")
        self.checkinGrid.addWidget(self.lbl_ci_phone, 1, 0, 1, 1)
        self.inp_ci_phone = QtWidgets.QLineEdit(parent=self.fra_checkin_form)
        self.inp_ci_phone.setObjectName("inp_ci_phone")
        self.checkinGrid.addWidget(self.inp_ci_phone, 1, 1, 1, 1)
        self.lbl_ci_room = QtWidgets.QLabel(parent=self.fra_checkin_form)
        self.lbl_ci_room.setObjectName("lbl_ci_room")
        self.checkinGrid.addWidget(self.lbl_ci_room, 1, 2, 1, 1)
        self.cmb_ci_room = QtWidgets.QComboBox(parent=self.fra_checkin_form)
        self.cmb_ci_room.setObjectName("cmb_ci_room")
        self.checkinGrid.addWidget(self.cmb_ci_room, 1, 3, 1, 1)
        self.lbl_ci_checkin_date = QtWidgets.QLabel(parent=self.fra_checkin_form)
        self.lbl_ci_checkin_date.setObjectName("lbl_ci_checkin_date")
        self.checkinGrid.addWidget(self.lbl_ci_checkin_date, 2, 0, 1, 1)
        self.de_ci_checkin = QtWidgets.QDateEdit(parent=self.fra_checkin_form)
        self.de_ci_checkin.setCalendarPopup(True)
        self.de_ci_checkin.setObjectName("de_ci_checkin")
        self.checkinGrid.addWidget(self.de_ci_checkin, 2, 1, 1, 1)
        self.lbl_ci_checkout_date = QtWidgets.QLabel(parent=self.fra_checkin_form)
        self.lbl_ci_checkout_date.setObjectName("lbl_ci_checkout_date")
        self.checkinGrid.addWidget(self.lbl_ci_checkout_date, 2, 2, 1, 1)
        self.de_ci_checkout = QtWidgets.QDateEdit(parent=self.fra_checkin_form)
        self.de_ci_checkout.setCalendarPopup(True)
        self.de_ci_checkout.setObjectName("de_ci_checkout")
        self.checkinGrid.addWidget(self.de_ci_checkout, 2, 3, 1, 1)
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setSpacing(12)
        self.hboxlayout.setObjectName("hboxlayout")
        self.btn_ci_confirm = QtWidgets.QPushButton(parent=self.fra_checkin_form)
        self.btn_ci_confirm.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 11px 36px;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover { background-color: #C9A84C; color: #1A2A4A; }\n"
"QPushButton:pressed { background-color: #0F1B30; }")
        self.btn_ci_confirm.setObjectName("btn_ci_confirm")
        self.hboxlayout.addWidget(self.btn_ci_confirm)
        self.btn_ci_cancel = QtWidgets.QPushButton(parent=self.fra_checkin_form)
        self.btn_ci_cancel.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    color: #A32D2D;\n"
"    border: 1.5px solid #A32D2D;\n"
"    border-radius: 8px;\n"
"    padding: 11px 28px;\n"
"    font-size: 13px;\n"
"}\n"
"QPushButton:hover { background-color: #FDECEA; }")
        self.btn_ci_cancel.setObjectName("btn_ci_cancel")
        self.hboxlayout.addWidget(self.btn_ci_cancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout.addItem(spacerItem2)
        self.checkinGrid.addLayout(self.hboxlayout, 3, 0, 1, 4)
        self.checkinPageLayout.addWidget(self.fra_checkin_form)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.checkinPageLayout.addItem(spacerItem3)
        self.stackedWidget.addWidget(self.pg_checkin)
        self.pg_checkout = QtWidgets.QWidget()
        self.pg_checkout.setObjectName("pg_checkout")
        self.checkoutPageLayout = QtWidgets.QVBoxLayout(self.pg_checkout)
        self.checkoutPageLayout.setContentsMargins(24, 20, 24, 20)
        self.checkoutPageLayout.setSpacing(14)
        self.checkoutPageLayout.setObjectName("checkoutPageLayout")
        self.hboxlayout1 = QtWidgets.QHBoxLayout()
        self.hboxlayout1.setObjectName("hboxlayout1")
        self.label = QtWidgets.QLabel(parent=self.pg_checkout)
        self.label.setStyleSheet("color:#1A2A4A; font-size:16px; font-weight:bold; border:none;")
        self.label.setObjectName("label")
        self.hboxlayout1.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout1.addItem(spacerItem4)
        self.btn_co_confirm = QtWidgets.QPushButton(parent=self.pg_checkout)
        self.btn_co_confirm.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"    padding: 9px 28px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover { background-color: #C9A84C; color: #1A2A4A; }\n"
"QPushButton:pressed { background-color: #0F1B30; }")
        self.btn_co_confirm.setObjectName("btn_co_confirm")
        self.hboxlayout1.addWidget(self.btn_co_confirm)
        self.checkoutPageLayout.addLayout(self.hboxlayout1)
        self.tbl_checkout_list = QtWidgets.QTableWidget(parent=self.pg_checkout)
        self.tbl_checkout_list.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F5F3EE;\n"
"    border: 1px solid #DDD8D0;\n"
"    border-radius: 8px;\n"
"    gridline-color: #E8E4DC;\n"
"    font-size: 13px;\n"
"    outline: none;\n"
"}\n"
"QTableWidget::item {\n"
"    padding: 9px 12px;\n"
"    color: #1A2B4A;\n"
"    border: none;\n"
"}\n"
"QTableWidget::item:selected {\n"
"    background-color: #D6E8F7;\n"
"    color: #1A2B4A;\n"
"}\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 10px 12px;\n"
"    border: none;\n"
"    border-right: 1px solid #2C3F60;\n"
"}\n"
"QHeaderView::section:first { border-top-left-radius: 7px; }\n"
"QHeaderView::section:last  { border-top-right-radius: 7px; border-right: none; }\n"
"QScrollBar:vertical {\n"
"    background: #F0EDE6; width: 8px; border-radius: 4px;\n"
"}\n"
"QScrollBar::handle:vertical { background: #C9A84C; border-radius: 4px; min-height: 30px; }\n"
"              ")
        self.tbl_checkout_list.setAlternatingRowColors(True)
        self.tbl_checkout_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tbl_checkout_list.setShowGrid(False)
        self.tbl_checkout_list.setObjectName("tbl_checkout_list")
        self.tbl_checkout_list.setColumnCount(7)
        self.tbl_checkout_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_checkout_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_checkout_list.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_checkout_list.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_checkout_list.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_checkout_list.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_checkout_list.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_checkout_list.setHorizontalHeaderItem(6, item)
        self.tbl_checkout_list.horizontalHeader().setStretchLastSection(True)
        self.tbl_checkout_list.verticalHeader().setVisible(False)
        self.checkoutPageLayout.addWidget(self.tbl_checkout_list)
        self.stackedWidget.addWidget(self.pg_checkout)
        self.pg_rooms = QtWidgets.QWidget()
        self.pg_rooms.setObjectName("pg_rooms")
        self.roomsPageLayout = QtWidgets.QVBoxLayout(self.pg_rooms)
        self.roomsPageLayout.setContentsMargins(24, 20, 24, 20)
        self.roomsPageLayout.setSpacing(14)
        self.roomsPageLayout.setObjectName("roomsPageLayout")
        self.hboxlayout2 = QtWidgets.QHBoxLayout()
        self.hboxlayout2.setObjectName("hboxlayout2")
        self.label1 = QtWidgets.QLabel(parent=self.pg_rooms)
        self.label1.setStyleSheet("color:#1A2A4A; font-size:16px; font-weight:bold; border:none;")
        self.label1.setObjectName("label1")
        self.hboxlayout2.addWidget(self.label1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout2.addItem(spacerItem5)
        self.inp_room_search = QtWidgets.QLineEdit(parent=self.pg_rooms)
        self.inp_room_search.setStyleSheet("QLineEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 1.5px solid #C5BFB5;\n"
"    border-radius: 20px;\n"
"    padding: 8px 16px 8px 36px;\n"
"    font-size: 13px;\n"
"    color: #1A2B4A;\n"
"    min-width: 240px;\n"
"}\n"
"QLineEdit:focus { border: 1.5px solid #C9A84C; background: #FFFEF9; }")
        self.inp_room_search.setObjectName("inp_room_search")
        self.hboxlayout2.addWidget(self.inp_room_search)
        self.roomsPageLayout.addLayout(self.hboxlayout2)
        self.tbl_rooms = QtWidgets.QTableWidget(parent=self.pg_rooms)
        self.tbl_rooms.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F5F3EE;\n"
"    border: 1px solid #DDD8D0;\n"
"    border-radius: 8px;\n"
"    gridline-color: #E8E4DC;\n"
"    font-size: 13px;\n"
"    outline: none;\n"
"}\n"
"QTableWidget::item { padding: 9px 12px; color: #1A2B4A; border: none; }\n"
"QTableWidget::item:selected { background-color: #D6E8F7; color: #1A2B4A; }\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    font-weight: bold;\n"
"    font-size: 13px;\n"
"    padding: 10px 12px;\n"
"    border: none;\n"
"    border-right: 1px solid #2C3F60;\n"
"}\n"
"QHeaderView::section:first { border-top-left-radius: 7px; }\n"
"QHeaderView::section:last  { border-top-right-radius: 7px; border-right: none; }\n"
"QScrollBar:vertical { background:#F0EDE6; width:8px; border-radius:4px; }\n"
"QScrollBar::handle:vertical { background:#C9A84C; border-radius:4px; min-height:30px; }\n"
"              ")
        self.tbl_rooms.setAlternatingRowColors(True)
        self.tbl_rooms.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tbl_rooms.setShowGrid(False)
        self.tbl_rooms.setObjectName("tbl_rooms")
        self.tbl_rooms.setColumnCount(5)
        self.tbl_rooms.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rooms.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rooms.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rooms.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rooms.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_rooms.setHorizontalHeaderItem(4, item)
        self.tbl_rooms.horizontalHeader().setStretchLastSection(True)
        self.tbl_rooms.verticalHeader().setVisible(False)
        self.roomsPageLayout.addWidget(self.tbl_rooms)
        self.stackedWidget.addWidget(self.pg_rooms)
        self.pg_services = QtWidgets.QWidget()
        self.pg_services.setObjectName("pg_services")
        self.svcPageLayout = QtWidgets.QVBoxLayout(self.pg_services)
        self.svcPageLayout.setContentsMargins(24, 20, 24, 20)
        self.svcPageLayout.setSpacing(14)
        self.svcPageLayout.setObjectName("svcPageLayout")
        self.hboxlayout3 = QtWidgets.QHBoxLayout()
        self.hboxlayout3.setObjectName("hboxlayout3")
        self.label2 = QtWidgets.QLabel(parent=self.pg_services)
        self.label2.setStyleSheet("color:#1A2A4A; font-size:16px; font-weight:bold; border:none;")
        self.label2.setObjectName("label2")
        self.hboxlayout3.addWidget(self.label2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout3.addItem(spacerItem6)
        self.btn_svc_add = QtWidgets.QPushButton(parent=self.pg_services)
        self.btn_svc_add.setStyleSheet("QPushButton {\n"
"    background-color: #1A2B4A;\n"
"    color: #FFFFFF;\n"
"    border: none;\n"
"    border-radius: 7px;\n"
"    padding: 9px 22px;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover { background-color: #C9A84C; color: #1A2A4A; }")
        self.btn_svc_add.setObjectName("btn_svc_add")
        self.hboxlayout3.addWidget(self.btn_svc_add)
        self.svcPageLayout.addLayout(self.hboxlayout3)
        self.tbl_services_used = QtWidgets.QTableWidget(parent=self.pg_services)
        self.tbl_services_used.setStyleSheet("QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    alternate-background-color: #F5F3EE;\n"
"    border: 1px solid #DDD8D0;\n"
"    border-radius: 8px;\n"
"    gridline-color: #E8E4DC;\n"
"    font-size: 13px;\n"
"    outline: none;\n"
"}\n"
"QTableWidget::item { padding: 9px 12px; color: #1A2B4A; border: none; }\n"
"QTableWidget::item:selected { background-color: #D6E8F7; color: #1A2B4A; }\n"
"QHeaderView::section {\n"
"    background-color: #1A2B4A; color: #FFFFFF;\n"
"    font-weight: bold; font-size: 13px;\n"
"    padding: 10px 12px; border: none; border-right: 1px solid #2C3F60;\n"
"}\n"
"QHeaderView::section:first { border-top-left-radius: 7px; }\n"
"QHeaderView::section:last  { border-top-right-radius: 7px; border-right: none; }\n"
"QScrollBar:vertical { background:#F0EDE6; width:8px; border-radius:4px; }\n"
"QScrollBar::handle:vertical { background:#C9A84C; border-radius:4px; min-height:30px; }\n"
"              ")
        self.tbl_services_used.setAlternatingRowColors(True)
        self.tbl_services_used.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tbl_services_used.setShowGrid(False)
        self.tbl_services_used.setObjectName("tbl_services_used")
        self.tbl_services_used.setColumnCount(5)
        self.tbl_services_used.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_services_used.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_services_used.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_services_used.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_services_used.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_services_used.setHorizontalHeaderItem(4, item)
        self.tbl_services_used.horizontalHeader().setStretchLastSection(True)
        self.tbl_services_used.verticalHeader().setVisible(False)
        self.svcPageLayout.addWidget(self.tbl_services_used)
        self.stackedWidget.addWidget(self.pg_services)
        self.pg_invoice = QtWidgets.QWidget()
        self.pg_invoice.setObjectName("pg_invoice")
        self.invoicePageLayout = QtWidgets.QVBoxLayout(self.pg_invoice)
        self.invoicePageLayout.setContentsMargins(24, 20, 24, 20)
        self.invoicePageLayout.setSpacing(14)
        self.invoicePageLayout.setObjectName("invoicePageLayout")
        self.lbl_invoice_page_title = QtWidgets.QLabel(parent=self.pg_invoice)
        self.lbl_invoice_page_title.setStyleSheet("color:#1A2A4A; font-size:16px; font-weight:bold; border:none;")
        self.lbl_invoice_page_title.setObjectName("lbl_invoice_page_title")
        self.invoicePageLayout.addWidget(self.lbl_invoice_page_title)
        self.hboxlayout4 = QtWidgets.QHBoxLayout()
        self.hboxlayout4.setSpacing(10)
        self.hboxlayout4.setObjectName("hboxlayout4")
        self.lbl_inv_search_hint = QtWidgets.QLabel(parent=self.pg_invoice)
        self.lbl_inv_search_hint.setStyleSheet("color:#1A2B4A; font-size:13px; border:none;")
        self.lbl_inv_search_hint.setObjectName("lbl_inv_search_hint")
        self.hboxlayout4.addWidget(self.lbl_inv_search_hint)
        self.inp_inv_search = QtWidgets.QLineEdit(parent=self.pg_invoice)
        self.inp_inv_search.setStyleSheet("QLineEdit {\n"
"    background: #FFFFFF; border: 1.5px solid #C5BFB5;\n"
"    border-radius: 7px; padding: 9px 14px;\n"
"    font-size: 13px; color: #1A2B4A; min-width: 260px;\n"
"}\n"
"QLineEdit:focus { border: 1.5px solid #C9A84C; }")
        self.inp_inv_search.setObjectName("inp_inv_search")
        self.hboxlayout4.addWidget(self.inp_inv_search)
        self.btn_inv_find = QtWidgets.QPushButton(parent=self.pg_invoice)
        self.btn_inv_find.setStyleSheet("QPushButton {\n"
"    background:#1A2B4A; color:#FFF; border:none;\n"
"    border-radius:7px; padding:9px 22px; font-size:13px; font-weight:bold;\n"
"}\n"
"QPushButton:hover { background:#C9A84C; color:#1A2A4A; }")
        self.btn_inv_find.setObjectName("btn_inv_find")
        self.hboxlayout4.addWidget(self.btn_inv_find)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.hboxlayout4.addItem(spacerItem7)
        self.invoicePageLayout.addLayout(self.hboxlayout4)
        self.invBodyLayout = QtWidgets.QHBoxLayout()
        self.invBodyLayout.setSpacing(16)
        self.invBodyLayout.setObjectName("invBodyLayout")
        self.widget_invoice = QtWidgets.QFrame(parent=self.pg_invoice)
        self.widget_invoice.setStyleSheet("QFrame#widget_invoice {\n"
"    background: #FFFFFF;\n"
"    border: 1px solid #DDD8D0;\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel { color: #1A2B4A; font-size: 13px; border: none; background: transparent; }")
        self.widget_invoice.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.widget_invoice.setObjectName("widget_invoice")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.widget_invoice)
        self.vboxlayout.setContentsMargins(18, 16, 18, 16)
        self.vboxlayout.setSpacing(8)
        self.vboxlayout.setObjectName("vboxlayout")
        self.lbl_inv_room = QtWidgets.QLabel(parent=self.widget_invoice)
        self.lbl_inv_room.setObjectName("lbl_inv_room")
        self.vboxlayout.addWidget(self.lbl_inv_room)
        self.lbl_inv_cust_name = QtWidgets.QLabel(parent=self.widget_invoice)
        self.lbl_inv_cust_name.setObjectName("lbl_inv_cust_name")
        self.vboxlayout.addWidget(self.lbl_inv_cust_name)
        self.lbl_inv_checkin = QtWidgets.QLabel(parent=self.widget_invoice)
        self.lbl_inv_checkin.setObjectName("lbl_inv_checkin")
        self.vboxlayout.addWidget(self.lbl_inv_checkin)
        self.lbl_inv_checkout = QtWidgets.QLabel(parent=self.widget_invoice)
        self.lbl_inv_checkout.setObjectName("lbl_inv_checkout")
        self.vboxlayout.addWidget(self.lbl_inv_checkout)
        self.tbl_inv_services = QtWidgets.QTableWidget(parent=self.widget_invoice)
        self.tbl_inv_services.setStyleSheet("QTableWidget {\n"
"    background:#FFFFFF; alternate-background-color:#F5F3EE;\n"
"    border: 1px solid #DDD8D0; border-radius:6px;\n"
"    gridline-color:#E8E4DC; font-size:13px; outline:none;\n"
"}\n"
"QTableWidget::item { padding:8px 10px; color:#1A2B4A; border:none; }\n"
"QTableWidget::item:selected { background:#D6E8F7; }\n"
"QHeaderView::section {\n"
"    background:#1A2B4A; color:#FFF; font-weight:bold; font-size:13px;\n"
"    padding:8px 10px; border:none; border-right:1px solid #2C3F60;\n"
"}\n"
"QHeaderView::section:first { border-top-left-radius:6px; }\n"
"QHeaderView::section:last  { border-top-right-radius:6px; border-right:none; }\n"
"                   ")
        self.tbl_inv_services.setAlternatingRowColors(True)
        self.tbl_inv_services.setShowGrid(False)
        self.tbl_inv_services.setObjectName("tbl_inv_services")
        self.tbl_inv_services.setColumnCount(4)
        self.tbl_inv_services.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inv_services.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inv_services.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inv_services.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_inv_services.setHorizontalHeaderItem(3, item)
        self.tbl_inv_services.horizontalHeader().setStretchLastSection(True)
        self.tbl_inv_services.verticalHeader().setVisible(False)
        self.vboxlayout.addWidget(self.tbl_inv_services)
        self.invBodyLayout.addWidget(self.widget_invoice)
        self.widget_3 = QtWidgets.QFrame(parent=self.pg_invoice)
        self.widget_3.setMinimumSize(QtCore.QSize(270, 0))
        self.widget_3.setMaximumSize(QtCore.QSize(300, 16777215))
        self.widget_3.setStyleSheet("QFrame#widget_3 {\n"
"    background: #FFFFFF;\n"
"    border: 1px solid #DDD8D0;\n"
"    border-radius: 10px;\n"
"}\n"
"QLabel { color: #1A2B4A; font-size: 13px; border: none; background: transparent; }\n"
"QRadioButton { color: #1A2B4A; font-size: 13px; border: none; background: transparent; }\n"
"QRadioButton::indicator { width: 16px; height: 16px; }\n"
"QRadioButton::indicator:checked { background: #1A2B4A; border-radius: 8px; border: 2px solid #C9A84C; }\n"
"                ")
        self.widget_3.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.widget_3.setObjectName("widget_3")
        self.vboxlayout1 = QtWidgets.QVBoxLayout(self.widget_3)
        self.vboxlayout1.setContentsMargins(18, 18, 18, 18)
        self.vboxlayout1.setSpacing(10)
        self.vboxlayout1.setObjectName("vboxlayout1")
        self.lbl_inv_room_charge = QtWidgets.QLabel(parent=self.widget_3)
        self.lbl_inv_room_charge.setObjectName("lbl_inv_room_charge")
        self.vboxlayout1.addWidget(self.lbl_inv_room_charge)
        self.lbl_inv_svc_charge = QtWidgets.QLabel(parent=self.widget_3)
        self.lbl_inv_svc_charge.setObjectName("lbl_inv_svc_charge")
        self.vboxlayout1.addWidget(self.lbl_inv_svc_charge)
        self.lbl_inv_vat = QtWidgets.QLabel(parent=self.widget_3)
        self.lbl_inv_vat.setObjectName("lbl_inv_vat")
        self.vboxlayout1.addWidget(self.lbl_inv_vat)
        self.frame = QtWidgets.QFrame(parent=self.widget_3)
        self.frame.setMinimumSize(QtCore.QSize(0, 1))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 1))
        self.frame.setStyleSheet("background: #C9A84C; border: none;")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.frame.setObjectName("frame")
        self.vboxlayout1.addWidget(self.frame)
        self.lbl_inv_total = QtWidgets.QLabel(parent=self.widget_3)
        self.lbl_inv_total.setStyleSheet("color:#1A2B4A; font-size:15px; font-weight:bold; border:none; background:transparent;")
        self.lbl_inv_total.setObjectName("lbl_inv_total")
        self.vboxlayout1.addWidget(self.lbl_inv_total)
        self.label3 = QtWidgets.QLabel(parent=self.widget_3)
        self.label3.setStyleSheet("color:#1A2B4A; font-size:13px; font-weight:bold; border:none; background:transparent; padding-top:4px;")
        self.label3.setObjectName("label3")
        self.vboxlayout1.addWidget(self.label3)
        self.rb_pay_cash = QtWidgets.QRadioButton(parent=self.widget_3)
        self.rb_pay_cash.setChecked(True)
        self.rb_pay_cash.setObjectName("rb_pay_cash")
        self.vboxlayout1.addWidget(self.rb_pay_cash)
        self.rb_pay_transfer = QtWidgets.QRadioButton(parent=self.widget_3)
        self.rb_pay_transfer.setObjectName("rb_pay_transfer")
        self.vboxlayout1.addWidget(self.rb_pay_transfer)
        self.rb_pay_card = QtWidgets.QRadioButton(parent=self.widget_3)
        self.rb_pay_card.setObjectName("rb_pay_card")
        self.vboxlayout1.addWidget(self.rb_pay_card)
        self.stk_payment_detail = QtWidgets.QStackedWidget(parent=self.widget_3)
        self.stk_payment_detail.setStyleSheet("background: transparent; border: none;")
        self.stk_payment_detail.setObjectName("stk_payment_detail")
        self.page_cash = QtWidgets.QWidget()
        self.page_cash.setObjectName("page_cash")
        self.vboxlayout2 = QtWidgets.QVBoxLayout(self.page_cash)
        self.vboxlayout2.setContentsMargins(0, 0, 0, 0)
        self.vboxlayout2.setSpacing(8)
        self.vboxlayout2.setObjectName("vboxlayout2")
        self.lbl_inv_cash_given_hint = QtWidgets.QLabel(parent=self.page_cash)
        self.lbl_inv_cash_given_hint.setObjectName("lbl_inv_cash_given_hint")
        self.vboxlayout2.addWidget(self.lbl_inv_cash_given_hint)
        self.inp_inv_cash_given = QtWidgets.QLineEdit(parent=self.page_cash)
        self.inp_inv_cash_given.setStyleSheet("QLineEdit {\n"
"    background:#F9F9F9; border:1.5px solid #D1D5DB;\n"
"    border-radius:7px; padding:9px 12px; font-size:13px; color:#1A2B4A;\n"
"}\n"
"QLineEdit:focus { border:1.5px solid #C9A84C; }")
        self.inp_inv_cash_given.setObjectName("inp_inv_cash_given")
        self.vboxlayout2.addWidget(self.inp_inv_cash_given)
        self.lbl_inv_change = QtWidgets.QLabel(parent=self.page_cash)
        self.lbl_inv_change.setObjectName("lbl_inv_change")
        self.vboxlayout2.addWidget(self.lbl_inv_change)
        self.stk_payment_detail.addWidget(self.page_cash)
        self.page_other = QtWidgets.QWidget()
        self.page_other.setObjectName("page_other")
        self.vboxlayout3 = QtWidgets.QVBoxLayout(self.page_other)
        self.vboxlayout3.setContentsMargins(0, 4, 0, 0)
        self.vboxlayout3.setObjectName("vboxlayout3")
        self.label4 = QtWidgets.QLabel(parent=self.page_other)
        self.label4.setStyleSheet("color:#8A9AB5; font-size:12px; font-style:italic; border:none; background:transparent;")
        self.label4.setObjectName("label4")
        self.vboxlayout3.addWidget(self.label4)
        self.stk_payment_detail.addWidget(self.page_other)
        self.vboxlayout1.addWidget(self.stk_payment_detail)
        spacerItem8 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.vboxlayout1.addItem(spacerItem8)
        self.hboxlayout5 = QtWidgets.QHBoxLayout()
        self.hboxlayout5.setSpacing(10)
        self.hboxlayout5.setObjectName("hboxlayout5")
        self.btn_inv_pay = QtWidgets.QPushButton(parent=self.widget_3)
        self.btn_inv_pay.setStyleSheet("QPushButton {\n"
"    background:#1A2B4A; color:#FFF; border:none;\n"
"    border-radius:8px; padding:11px 20px; font-size:13px; font-weight:bold;\n"
"}\n"
"QPushButton:hover { background:#C9A84C; color:#1A2A4A; }")
        self.btn_inv_pay.setObjectName("btn_inv_pay")
        self.hboxlayout5.addWidget(self.btn_inv_pay)
        self.btn_inv_print = QtWidgets.QPushButton(parent=self.widget_3)
        self.btn_inv_print.setStyleSheet("QPushButton {\n"
"    background:#FFF; color:#1A2B4A; border:1.5px solid #1A2B4A;\n"
"    border-radius:8px; padding:11px 14px; font-size:13px;\n"
"}\n"
"QPushButton:hover { background:#EAF2FB; border-color:#C9A84C; }")
        self.btn_inv_print.setObjectName("btn_inv_print")
        self.hboxlayout5.addWidget(self.btn_inv_print)
        self.vboxlayout1.addLayout(self.hboxlayout5)
        self.invBodyLayout.addWidget(self.widget_3)
        self.invoicePageLayout.addLayout(self.invBodyLayout)
        self.stackedWidget.addWidget(self.pg_invoice)
        self.pg_profile = QtWidgets.QWidget()
        self.pg_profile.setObjectName("pg_profile")
        self.profilePageLayout = QtWidgets.QVBoxLayout(self.pg_profile)
        self.profilePageLayout.setContentsMargins(24, 20, 24, 20)
        self.profilePageLayout.setSpacing(16)
        self.profilePageLayout.setObjectName("profilePageLayout")
        self.label5 = QtWidgets.QLabel(parent=self.pg_profile)
        self.label5.setStyleSheet("color:#1A2A4A; font-size:16px; font-weight:bold; border:none;")
        self.label5.setObjectName("label5")
        self.profilePageLayout.addWidget(self.label5)
        self.frame1 = QtWidgets.QFrame(parent=self.pg_profile)
        self.frame1.setMaximumSize(QtCore.QSize(540, 16777215))
        self.frame1.setStyleSheet("QFrame {\n"
"    background:#FFFFFF; border:1px solid #DDD8D0; border-radius:12px;\n"
"}\n"
"QLabel { color:#1A2B4A; font-size:13px; font-weight:bold; border:none; background:transparent; }\n"
"QLineEdit {\n"
"    background:#F9F9F9; border:1.5px solid #D1D5DB;\n"
"    border-radius:7px; padding:9px 12px; font-size:13px; color:#1A2B4A;\n"
"}\n"
"QLineEdit:focus { border:1.5px solid #C9A84C; background:#FFFEF9; }\n"
"              ")
        self.frame1.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame1.setObjectName("frame1")
        self.formlayout = QtWidgets.QFormLayout(self.frame1)
        self.formlayout.setContentsMargins(28, 24, 28, 24)
        self.formlayout.setHorizontalSpacing(18)
        self.formlayout.setVerticalSpacing(14)
        self.formlayout.setObjectName("formlayout")
        self.lbl_pf_name = QtWidgets.QLabel(parent=self.frame1)
        self.lbl_pf_name.setObjectName("lbl_pf_name")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_pf_name)
        self.inp_pf_fullname = QtWidgets.QLineEdit(parent=self.frame1)
        self.inp_pf_fullname.setObjectName("inp_pf_fullname")
        self.formlayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inp_pf_fullname)
        self.lbl_pf_phone = QtWidgets.QLabel(parent=self.frame1)
        self.lbl_pf_phone.setObjectName("lbl_pf_phone")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.lbl_pf_phone)
        self.inp_pf_phone = QtWidgets.QLineEdit(parent=self.frame1)
        self.inp_pf_phone.setObjectName("inp_pf_phone")
        self.formlayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inp_pf_phone)
        self.lbl_pf_change_pass_title = QtWidgets.QLabel(parent=self.frame1)
        self.lbl_pf_change_pass_title.setStyleSheet("color:#C9A84C; font-size:13px; font-weight:bold; padding-top:10px; border:none; background:transparent;")
        self.lbl_pf_change_pass_title.setObjectName("lbl_pf_change_pass_title")
        self.formlayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.SpanningRole, self.lbl_pf_change_pass_title)
        self.label6 = QtWidgets.QLabel(parent=self.frame1)
        self.label6.setObjectName("label6")
        self.formlayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label6)
        self.inp_pf_old_pass = QtWidgets.QLineEdit(parent=self.frame1)
        self.inp_pf_old_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.inp_pf_old_pass.setObjectName("inp_pf_old_pass")
        self.formlayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inp_pf_old_pass)
        self.label7 = QtWidgets.QLabel(parent=self.frame1)
        self.label7.setObjectName("label7")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label7)
        self.inp_pf_new_pass = QtWidgets.QLineEdit(parent=self.frame1)
        self.inp_pf_new_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.inp_pf_new_pass.setObjectName("inp_pf_new_pass")
        self.formlayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inp_pf_new_pass)
        self.label8 = QtWidgets.QLabel(parent=self.frame1)
        self.label8.setObjectName("label8")
        self.formlayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label8)
        self.inp_pf_confirm_pass = QtWidgets.QLineEdit(parent=self.frame1)
        self.inp_pf_confirm_pass.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.inp_pf_confirm_pass.setObjectName("inp_pf_confirm_pass")
        self.formlayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.inp_pf_confirm_pass)
        self.btn_pf_save = QtWidgets.QPushButton(parent=self.frame1)
        self.btn_pf_save.setStyleSheet("QPushButton {\n"
"    background:#1A2B4A; color:#FFF; border:none;\n"
"    border-radius:8px; padding:11px 28px; font-size:13px; font-weight:bold;\n"
"}\n"
"QPushButton:hover { background:#C9A84C; color:#1A2A4A; }")
        self.btn_pf_save.setObjectName("btn_pf_save")
        self.formlayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btn_pf_save)
        self.profilePageLayout.addWidget(self.frame1)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.profilePageLayout.addItem(spacerItem9)
        self.stackedWidget.addWidget(self.pg_profile)
        self.mainLayout.addWidget(self.stackedWidget)
        self.rootLayout.addWidget(self.MainContent)
        StaffWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(StaffWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.stk_payment_detail.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(StaffWindow)

    def retranslateUi(self, StaffWindow):
        _translate = QtCore.QCoreApplication.translate
        StaffWindow.setWindowTitle(_translate("StaffWindow", "Hotel Staff"))
        self.lbl_app_title.setText(_translate("StaffWindow", "🏨  HOTEL STAFF"))
        self.btn_nav_checkin.setText(_translate("StaffWindow", "  📋  Đặt Phòng"))
        self.btn_nav_checkout.setText(_translate("StaffWindow", "  🚪  Trả Phòng"))
        self.btn_nav_rooms.setText(_translate("StaffWindow", "  🛏  Danh Sách Phòng"))
        self.btn_nav_invoice.setText(_translate("StaffWindow", "  💳  Hóa Đơn"))
        self.btn_nav_service.setText(_translate("StaffWindow", "  🧾  Dịch Vụ"))
        self.btn_nav_profile.setText(_translate("StaffWindow", "  👤  Tài Khoản"))
        self.btn_logout.setText(_translate("StaffWindow", "  🚪  Đăng Xuất"))
        self.lbl_header_title.setText(_translate("StaffWindow", "Quản Lý Phòng Khách Sạn"))
        self.lbl_current_user.setText(_translate("StaffWindow", "👤  Staff"))
        self.lbl_checkin_page_title.setText(_translate("StaffWindow", "📋  Đặt Phòng / Check-in"))
        self.lbl_ci_name.setText(_translate("StaffWindow", "Họ và Tên *"))
        self.inp_ci_name.setPlaceholderText(_translate("StaffWindow", "Nhập họ tên khách..."))
        self.lbl_ci_idcard.setText(_translate("StaffWindow", "Số CCCD *"))
        self.inp_ci_idcard.setPlaceholderText(_translate("StaffWindow", "Số CCCD / CMND..."))
        self.lbl_ci_phone.setText(_translate("StaffWindow", "Điện Thoại *"))
        self.inp_ci_phone.setPlaceholderText(_translate("StaffWindow", "Số điện thoại..."))
        self.lbl_ci_room.setText(_translate("StaffWindow", "Chọn Phòng *"))
        self.lbl_ci_checkin_date.setText(_translate("StaffWindow", "Ngày Nhận Phòng"))
        self.lbl_ci_checkout_date.setText(_translate("StaffWindow", "Ngày Trả Phòng"))
        self.btn_ci_confirm.setText(_translate("StaffWindow", "✅  Xác Nhận Check-in"))
        self.btn_ci_cancel.setText(_translate("StaffWindow", "🗑  Hủy Booking"))
        self.label.setText(_translate("StaffWindow", "🚪  Danh Sách Phòng Đang Thuê"))
        self.btn_co_confirm.setText(_translate("StaffWindow", "✅  Xác Nhận Check-out"))
        item = self.tbl_checkout_list.horizontalHeaderItem(0)
        item.setText(_translate("StaffWindow", "Phòng"))
        item = self.tbl_checkout_list.horizontalHeaderItem(1)
        item.setText(_translate("StaffWindow", "Khách Hàng"))
        item = self.tbl_checkout_list.horizontalHeaderItem(2)
        item.setText(_translate("StaffWindow", "Check-in"))
        item = self.tbl_checkout_list.horizontalHeaderItem(3)
        item.setText(_translate("StaffWindow", "Check-out"))
        item = self.tbl_checkout_list.horizontalHeaderItem(4)
        item.setText(_translate("StaffWindow", "Dịch Vụ"))
        item = self.tbl_checkout_list.horizontalHeaderItem(5)
        item.setText(_translate("StaffWindow", "Tạm Tính"))
        item = self.tbl_checkout_list.horizontalHeaderItem(6)
        item.setText(_translate("StaffWindow", "Trạng Thái"))
        self.label1.setText(_translate("StaffWindow", "🛏  Danh Sách Phòng"))
        self.inp_room_search.setPlaceholderText(_translate("StaffWindow", "🔍  Tìm kiếm..."))
        item = self.tbl_rooms.horizontalHeaderItem(0)
        item.setText(_translate("StaffWindow", "Số Phòng"))
        item = self.tbl_rooms.horizontalHeaderItem(1)
        item.setText(_translate("StaffWindow", "Loại Phòng"))
        item = self.tbl_rooms.horizontalHeaderItem(2)
        item.setText(_translate("StaffWindow", "Tầng"))
        item = self.tbl_rooms.horizontalHeaderItem(3)
        item.setText(_translate("StaffWindow", "Giá / Đêm"))
        item = self.tbl_rooms.horizontalHeaderItem(4)
        item.setText(_translate("StaffWindow", "Trạng Thái"))
        self.label2.setText(_translate("StaffWindow", "🧾  Dịch Vụ Đang Sử Dụng"))
        self.btn_svc_add.setText(_translate("StaffWindow", "➕  Thêm Dịch Vụ"))
        item = self.tbl_services_used.horizontalHeaderItem(0)
        item.setText(_translate("StaffWindow", "Phòng"))
        item = self.tbl_services_used.horizontalHeaderItem(1)
        item.setText(_translate("StaffWindow", "Dịch Vụ"))
        item = self.tbl_services_used.horizontalHeaderItem(2)
        item.setText(_translate("StaffWindow", "Số Lượng"))
        item = self.tbl_services_used.horizontalHeaderItem(3)
        item.setText(_translate("StaffWindow", "Đơn Giá"))
        item = self.tbl_services_used.horizontalHeaderItem(4)
        item.setText(_translate("StaffWindow", "Thành Tiền"))
        self.lbl_invoice_page_title.setText(_translate("StaffWindow", "💳  Hóa Đơn Thanh Toán"))
        self.lbl_inv_search_hint.setText(_translate("StaffWindow", "Tìm theo số phòng / tên khách:"))
        self.inp_inv_search.setPlaceholderText(_translate("StaffWindow", "Nhập số phòng hoặc tên khách..."))
        self.btn_inv_find.setText(_translate("StaffWindow", "🔍  Tìm"))
        self.lbl_inv_room.setText(_translate("StaffWindow", "Phòng:"))
        self.lbl_inv_cust_name.setText(_translate("StaffWindow", "Họ Tên:"))
        self.lbl_inv_checkin.setText(_translate("StaffWindow", "Check-in:"))
        self.lbl_inv_checkout.setText(_translate("StaffWindow", "Check-out:"))
        item = self.tbl_inv_services.horizontalHeaderItem(0)
        item.setText(_translate("StaffWindow", "Dịch Vụ"))
        item = self.tbl_inv_services.horizontalHeaderItem(1)
        item.setText(_translate("StaffWindow", "SL"))
        item = self.tbl_inv_services.horizontalHeaderItem(2)
        item.setText(_translate("StaffWindow", "Đơn Giá"))
        item = self.tbl_inv_services.horizontalHeaderItem(3)
        item.setText(_translate("StaffWindow", "Thành Tiền"))
        self.lbl_inv_room_charge.setText(_translate("StaffWindow", "Tiền Phòng:  —"))
        self.lbl_inv_svc_charge.setText(_translate("StaffWindow", "Dịch Vụ:  —"))
        self.lbl_inv_vat.setText(_translate("StaffWindow", "VAT (8%):  —"))
        self.lbl_inv_total.setText(_translate("StaffWindow", "Tổng Cộng:  —"))
        self.label3.setText(_translate("StaffWindow", "Phương Thức Thanh Toán:"))
        self.rb_pay_cash.setText(_translate("StaffWindow", "  💵  Tiền Mặt"))
        self.rb_pay_transfer.setText(_translate("StaffWindow", "  🏦  Chuyển Khoản"))
        self.rb_pay_card.setText(_translate("StaffWindow", "  💳  Thẻ"))
        self.lbl_inv_cash_given_hint.setText(_translate("StaffWindow", "Tiền Khách Đưa:"))
        self.inp_inv_cash_given.setPlaceholderText(_translate("StaffWindow", "Nhập số tiền..."))
        self.lbl_inv_change.setText(_translate("StaffWindow", "Tiền Thừa:"))
        self.label4.setText(_translate("StaffWindow", "Thanh toán không dùng tiền mặt"))
        self.btn_inv_pay.setText(_translate("StaffWindow", "✅  Thanh Toán"))
        self.btn_inv_print.setText(_translate("StaffWindow", "🖨️  In"))
        self.label5.setText(_translate("StaffWindow", "👤  Thông Tin Cá Nhân"))
        self.lbl_pf_name.setText(_translate("StaffWindow", "Họ và Tên"))
        self.lbl_pf_phone.setText(_translate("StaffWindow", "Điện Thoại"))
        self.inp_pf_phone.setPlaceholderText(_translate("StaffWindow", "Số điện thoại..."))
        self.lbl_pf_change_pass_title.setText(_translate("StaffWindow", "── Đổi Mật Khẩu ──────────────────"))
        self.label6.setText(_translate("StaffWindow", "Mật Khẩu Cũ"))
        self.label7.setText(_translate("StaffWindow", "Mật Khẩu Mới"))
        self.label8.setText(_translate("StaffWindow", "Xác Nhận MK Mới"))
        self.btn_pf_save.setText(_translate("StaffWindow", "💾  Lưu Thay Đổi"))
